### ISSUE TITLE
Improve List Structure for Faster Existence Checking

### ISSUE THREAD

**Issue by Levy-from-Odessa** [mastermunj/global-tld-list#1141]
The current list structure used for existence checking in the codebase relies on the indexOf function, which has a time complexity of _O(n)_ and can result in slower performance as the list grows larger.

To enhance efficiency, I suggest rewriting the list as an object with **key-value pairs**, enabling faster existence checking using a hash lookup with a time complexity of _O(1)_. This modification would significantly improve performance, simplify the code.

Thank you for your package and for reviewing the issue.

**Comment by mastermunj** [comment]
Thank you for the suggestion @Levy-from-Odessa. Resolved this with #1143. It's part of v1.0.0 release.
